---
blank_issues_enabled: false
{% if cookiecutter.use_github_discussions == 'y' -%}
contact_links:
  - name: {{cookiecutter.project_name}} Community Support
    url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.repo_slug}}/discussions
    about: Please ask and answer questions here.
{% endif %}