---
name: Build template

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install cookiecutter
        run: |
          pip install cookiecutter
      - name: Invoke cookiecutter
        run: >-
          cookiecutter .
          --overwrite-if-exists
          --no-input
          project_name="PROJECT_NAME"
          repo_slug="REPO_SLUG"
          github_username="GITHUB_USERNAME"
          full_name="FULL_NAME"
          open_source_license="OPEN_SOURCE_LICENSE"
          modern_header="y"
          table_in_about="n"
          include_logo="y"
          include_badges="y"
          include_toc="y"
          include_screenshots="y"
          include_project_assistance="y"
          include_authors="y"
          include_security="y"
          include_acknowledgements="y"
          include_code_of_conduct="y"
          include_workflows="y"
          use_codeql="y"
          use_conventional_commits="y"
          use_github_discussions="n"
      # - name: Lint markdown files
      #   uses: nosborn/github-action-markdown-cli@master
      #   with:
      #     files: REPO_SLUG/
      #     config_file: ".markdownlint.json"
      - name: Compress the template folder
        uses: papeloto/action-zip@v1
        with:
          files: REPO_SLUG/
          dest: template.zip
      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "🏗️ Precompiled template"
          files: |
            template.zip
